name: ROS 2 CI
on:
  push:
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Install ROS 2 humble packages
          run: |
            sudo apt update && sudo apt install curl -y
            export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
            curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" # If using Ubuntu derivates use $UBUNTU_CODENAME
            sudo apt install /tmp/ros2-apt-source.deb
            sudo apt update
            sudo apt install ros-humble-desktop
            sudo apt install ros-humble-ros-base

      - name: Setup Workspace
          run: |
            source /opt/ros/humble/setup.bash
            mkdir -p ros_ws/src/project_legion
            cd ros_ws
            colcon build
            source install/setup.bash
            

