name: Test_docker
on:
  push:

jobs:
  build_docker:
    name: build using docker
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-desktop-full-jammy

    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: stmoon/github_action_tutorial
          path: ros_ws/src/github_action_tutorial

      - name: Build
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros_ws
          # rosdep update
          # rosdep install --from-paths src -y --ignore-src
          colcon build

      - name: Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros_ws
          source install/setup.bash
          colcon test
          colcon test-result --verbose