name: Test2
on:
  push:
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Install ROS2
        run: |
          sudo apt update && sudo apt install curl -y
          export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
          curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" # If using Ubuntu derivates use $UBUNTU_CODENAME
          sudo apt install /tmp/ros2-apt-source.deb
          sudo apt update
          sudo rosdep init
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ros-humble-desktop ros-humble-ros-base ros-dev-tools
          version: 1.0
