name: Test2
on:
  push:
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Install ROS2
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ros-humble-desktop ros-humble-ros-base ros-dev-tools
          version: 1.0
