name: Test_docker
on:
  push:
jobs:
  build_docker:
    name: build using docker
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
          required-ros-distributions: jazzy
